version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbit-init:
    build: .
    command: python api/init_rabbit.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      rabbit-init:
        condition: service_completed_successfully

  email_worker:
    build: .
    command: python workers/email_worker.py
    depends_on:
      rabbit-init:
        condition: service_completed_successfully
    volumes:
      - ./logs:/app/logs

  sms_worker:
    build: .
    command: python workers/sms_worker.py
    depends_on:
      rabbit-init:
        condition: service_completed_successfully
    volumes:
      - ./logs:/app/logs

  log_worker:
    build: .
    command: python workers/log_worker.py
    depends_on:
      rabbit-init:
        condition: service_completed_successfully
    volumes:
      - ./logs:/app/logs
